// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ncuerkukueczqczeuppu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5jdWVya3VrdWVjenFjemV1cHB1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3MDI4NjEsImV4cCI6MjA2NzI3ODg2MX0.dXc8exZBpGgRiM8DBV_yBKGI6BQRKSYGcSaM8dDWKAc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});